package provider

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/willemharingopti/terraform-provider-optimizelycmssaas/internal/client"
)

var (
	_ resource.Resource                = &blueprintResource{}
	_ resource.ResourceWithConfigure   = &blueprintResource{}
	_ resource.ResourceWithImportState = &blueprintResource{}
)

func NewBlueprintResource() resource.Resource { return &blueprintResource{} }

type blueprintResource struct{ c *client.Client }

type blueprintModel struct {
	Key         types.String `tfsdk:"key"`
	DisplayName types.String `tfsdk:"display_name"`
	ContentType types.String `tfsdk:"content_type"`
	ContentJSON types.String `tfsdk:"content_json"`
}

func (r *blueprintResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_blueprint"
}

func (r *blueprintResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A blueprint: a template of property values used when creating new content.",
		Attributes: map[string]schema.Attribute{
			"key": schema.StringAttribute{
				Optional: true, Computed: true,
				Description: "Unique key; generated by the CMS when omitted. Cannot be changed.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(), stringplanmodifier.RequiresReplace(),
				},
			},
			"display_name": schema.StringAttribute{Required: true, Description: "Name shown when choosing a blueprint."},
			"content_type": schema.StringAttribute{
				Required: true, Description: "Content type the blueprint is for. Cannot be changed.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"content_json": schema.StringAttribute{
				Required: true,
				Description: "JSON object with the blueprint data: {\"properties\": {\"title\": {\"value\": \"...\"}}} (every property value is wrapped as {value = ...}) and optionally binding and composition " +
					"(use jsonencode). Fields the API adds as defaults are ignored when detecting drift.",
			},
		},
	}
}

func (r *blueprintResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.c = clientFrom(req.ProviderData, &resp.Diagnostics)
}

func blueprintFromAPI(b *client.Blueprint, prior types.String) blueprintModel {
	var remote any
	_ = json.Unmarshal(b.Content, &remote)
	return blueprintModel{
		Key:         types.StringValue(b.Key),
		DisplayName: types.StringValue(b.DisplayName),
		ContentType: types.StringValue(b.ContentType),
		ContentJSON: reconcileJSON(prior, remote),
	}
}

func (r *blueprintResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan blueprintModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := parseObject(plan.ContentJSON); err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("content_json"), "Invalid JSON", "content_json must be a JSON object: "+err.Error())
		return
	}
	in := &client.Blueprint{
		DisplayName: plan.DisplayName.ValueString(), ContentType: plan.ContentType.ValueString(),
		Content: json.RawMessage(plan.ContentJSON.ValueString()),
	}
	if !plan.Key.IsUnknown() {
		in.Key = plan.Key.ValueString()
	}
	out, err := r.c.Blueprints.Create(ctx, in.Key, in)
	if err != nil {
		resp.Diagnostics.AddError("Creating blueprint failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, blueprintFromAPI(out, plan.ContentJSON))...)
}

func (r *blueprintResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state blueprintModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, err := r.c.Blueprints.Get(ctx, state.Key.ValueString())
	if errors.Is(err, client.ErrNotFound) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Reading blueprint failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, blueprintFromAPI(out, state.ContentJSON))...)
}

func (r *blueprintResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state blueprintModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	newC, err1 := parseObject(plan.ContentJSON)
	oldC, err2 := parseObject(state.ContentJSON)
	if err := errors.Join(err1, err2); err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("content_json"), "Invalid JSON", err.Error())
		return
	}
	patch := map[string]any{"displayName": plan.DisplayName.ValueString()}
	if content := mergePatchDiff(oldC, newC); len(content) > 0 {
		patch["content"] = content
	}
	key := state.Key.ValueString() // plan.Key may be unknown
	out, err := r.c.Blueprints.Patch(ctx, key, patch)
	if err != nil {
		resp.Diagnostics.AddError("Updating blueprint failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, blueprintFromAPI(out, plan.ContentJSON))...)
}

func (r *blueprintResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state blueprintModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.c.Blueprints.Delete(ctx, state.Key.ValueString()); err != nil && !errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddError("Deleting blueprint failed", err.Error())
	}
}

func (r *blueprintResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("key"), req.ID)...)
}
