package provider

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/willemharingopti/terraform-provider-optimizelycmssaas/internal/client"
)

var (
	_ resource.Resource                = &contentResource{}
	_ resource.ResourceWithConfigure   = &contentResource{}
	_ resource.ResourceWithImportState = &contentResource{}
)

const statusPublished = "published"

func NewContentResource() resource.Resource { return &contentResource{} }

type contentResource struct{ c *client.Client }

// contentModel is a content item plus ONE locale's current version. Manage
// additional locales of an existing item are not supported yet (each resource creates its item).
type contentModel struct {
	Key             types.String `tfsdk:"key"`
	ContentType     types.String `tfsdk:"content_type"`
	Container       types.String `tfsdk:"container"`
	Owner           types.String `tfsdk:"owner"`
	Blueprint       types.String `tfsdk:"blueprint"`
	Locale          types.String `tfsdk:"locale"`
	DisplayName     types.String `tfsdk:"display_name"`
	RouteSegment    types.String `tfsdk:"route_segment"`
	SimpleRoute     types.String `tfsdk:"simple_route"`
	PropertiesJSON  types.String `tfsdk:"properties_json"`
	Publish         types.Bool   `tfsdk:"publish"`
	PermanentDelete types.Bool   `tfsdk:"permanent_delete"`
	Version         types.String `tfsdk:"version"`
	Status          types.String `tfsdk:"status"`
	Reference       types.String `tfsdk:"reference"`
}

func (r *contentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_content"
}

func (r *contentResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	keep := []planmodifier.String{stringplanmodifier.UseStateForUnknown()}
	keepReplace := []planmodifier.String{stringplanmodifier.UseStateForUnknown(), stringplanmodifier.RequiresReplace()}
	resp.Schema = schema.Schema{
		Description: "A content item and the current version of one locale. Updating a published version " +
			"creates a new version; set publish = true to publish it.",
		Attributes: map[string]schema.Attribute{
			"key": schema.StringAttribute{
				Optional: true, Computed: true, PlanModifiers: keepReplace,
				Description: "Content key; generated by the CMS when omitted. Cannot be changed.",
			},
			"content_type": schema.StringAttribute{
				Required: true, Description: "Content type key. Cannot be changed.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"container": schema.StringAttribute{
				Optional: true, Computed: true, PlanModifiers: keep,
				Description: "Key of the parent content item. Can be changed to move the item.",
			},
			"owner": schema.StringAttribute{
				Optional: true, Computed: true, PlanModifiers: keep,
				Description: "Key of the owning content item (for assets).",
			},
			"blueprint": schema.StringAttribute{
				Optional: true, Description: "Blueprint key to create from. Create-only; not returned by the API.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"locale": schema.StringAttribute{
				Optional: true, Computed: true, PlanModifiers: keepReplace,
				Description: "BCP-47 locale of this version. Cannot be changed.",
			},
			"display_name":  schema.StringAttribute{Required: true, Description: "Name of the content item in this locale."},
			"route_segment": schema.StringAttribute{Optional: true, Computed: true, Description: "URL segment; generated when omitted."},
			"simple_route":  schema.StringAttribute{Optional: true, Description: "Shortcut URL for pages and experiences."},
			"properties_json": schema.StringAttribute{
				Optional: true,
				Description: "JSON object of property values keyed by property name (use jsonencode); each value is wrapped as {value = ...}, e.g. {title = {value = \"Hello\"}}. " +
					"Drift is detected structurally; fields the API adds as defaults are ignored.",
			},
			"publish": schema.BoolAttribute{
				Optional: true, Computed: true, Default: booldefault.StaticBool(false),
				Description: "Publish the version after each apply. Publishing is one-way: setting this back to false does not unpublish.",
			},
			"permanent_delete": schema.BoolAttribute{
				Optional: true, Computed: true, Default: booldefault.StaticBool(false),
				Description: "Delete permanently on destroy instead of moving to the CMS's recoverable deleted state.",
			},
			"reference": schema.StringAttribute{
				Computed: true, PlanModifiers: keep,
				Description: "The item as a content reference, cms://content/<key>. Use as an application's `entry_point`.",
			},
			"version": schema.StringAttribute{Computed: true, Description: "Identifier of the managed version."},
			"status":  schema.StringAttribute{Computed: true, Description: "Status of the managed version, e.g. draft, published."},
		},
	}
}

func (r *contentResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.c = clientFrom(req.ProviderData, &resp.Diagnostics)
}

func rawProps(m map[string]any) map[string]json.RawMessage {
	if m == nil {
		return nil
	}
	out := make(map[string]json.RawMessage, len(m))
	for k, v := range m {
		b, _ := json.Marshal(v)
		out[k] = b
	}
	return out
}

func contentFromAPI(n *client.ContentNode, v *client.ContentVersion, prior contentModel) contentModel {
	remote := map[string]any{}
	for k, raw := range v.Properties {
		var x any
		_ = json.Unmarshal(raw, &x)
		remote[k] = x
	}
	return contentModel{
		Key:             types.StringValue(n.Key),
		ContentType:     types.StringValue(n.ContentType),
		Container:       strOrNull(n.Container),
		Owner:           strOrNull(n.Owner),
		Blueprint:       prior.Blueprint,
		Locale:          strOrNull(v.Locale),
		DisplayName:     types.StringValue(v.DisplayName),
		RouteSegment:    strOrNull(v.RouteSegment),
		SimpleRoute:     strOrNull(v.SimpleRoute),
		PropertiesJSON:  reconcileJSON(prior.PropertiesJSON, remote),
		Publish:         prior.Publish,
		PermanentDelete: prior.PermanentDelete,
		Version:         types.StringValue(v.Version),
		Status:          types.StringValue(v.Status),
		Reference:       types.StringValue("cms://content/" + n.Key),
	}
}

// publishIfRequested publishes v when asked and not already published.
func (r *contentResource) publishIfRequested(ctx context.Context, key string, v *client.ContentVersion, publish bool) (*client.ContentVersion, error) {
	if !publish || v.Status == statusPublished {
		return v, nil
	}
	published, err := r.c.PublishVersion(ctx, key, v.Version)
	if err != nil {
		return nil, err
	}
	if published.Status != statusPublished {
		return nil, fmt.Errorf("the publish request was accepted but version %s is %q, not published "+
			"(approvals may be required, or a publish is scheduled)", published.Version, published.Status)
	}
	return published, nil
}

func (r *contentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan contentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	props, err := parseObject(plan.PropertiesJSON)
	if err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("properties_json"), "Invalid JSON", "properties_json must be a JSON object: "+err.Error())
		return
	}
	in := &client.NewContent{
		ContentType: plan.ContentType.ValueString(),
		Blueprint:   plan.Blueprint.ValueString(),
		InitialVersion: client.ContentVersion{
			DisplayName: plan.DisplayName.ValueString(), SimpleRoute: plan.SimpleRoute.ValueString(), Properties: rawProps(props),
		},
	}
	// Computed attributes are unknown on create: send only what was configured.
	if !plan.Key.IsUnknown() {
		in.Key = plan.Key.ValueString()
	}
	if !plan.Container.IsUnknown() {
		in.Container = plan.Container.ValueString()
	}
	if !plan.Owner.IsUnknown() {
		in.Owner = plan.Owner.ValueString()
	}
	if !plan.Locale.IsUnknown() {
		in.InitialVersion.Locale = plan.Locale.ValueString()
	}
	if !plan.RouteSegment.IsUnknown() {
		in.InitialVersion.RouteSegment = plan.RouteSegment.ValueString()
	}

	created, err := r.c.CreateContent(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Creating content failed", err.Error())
		return
	}
	ver := created.InitialVersion
	if ver.Version == "" {
		resp.Diagnostics.AddError("Creating content failed", "the API did not return the initial version")
		return
	}
	// The item exists from here on; save state before further steps so a failure
	// below does not orphan it.
	node := &created.ContentNode
	resp.Diagnostics.Append(resp.State.Set(ctx, contentFromAPI(node, &ver, plan))...)

	published, err := r.publishIfRequested(ctx, node.Key, &ver, plan.Publish.ValueBool())
	if err != nil {
		resp.Diagnostics.AddError("Publishing content failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, contentFromAPI(node, published, plan))...)
}

// currentVersion finds the version to manage: the recorded one, or on import the
// most recently modified version of the primary locale.
func (r *contentResource) currentVersion(ctx context.Context, node *client.ContentNode, state contentModel) (*client.ContentVersion, error) {
	if v := state.Version.ValueString(); v != "" {
		return r.c.GetVersion(ctx, node.Key, v)
	}
	locale := state.Locale.ValueString()
	if locale == "" {
		locale = node.PrimaryLocale
	}
	versions, err := r.c.ListVersions(ctx, node.Key, locale)
	if err != nil {
		return nil, err
	}
	if len(versions) == 0 {
		return nil, fmt.Errorf("content %q has no versions for locale %q", node.Key, locale)
	}
	best := versions[0]
	for _, v := range versions[1:] {
		if v.LastModified > best.LastModified { // RFC 3339, same offset: lexical order
			best = v
		}
	}
	return &best, nil
}

func (r *contentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state contentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	node, err := r.c.GetContent(ctx, state.Key.ValueString())
	if errors.Is(err, client.ErrNotFound) || (err == nil && node.Deleted != nil) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Reading content failed", err.Error())
		return
	}
	ver, err := r.currentVersion(ctx, node, state)
	if errors.Is(err, client.ErrNotFound) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Reading content version failed", err.Error())
		return
	}
	if state.Publish.IsNull() {
		state.Publish = types.BoolValue(false)
	}
	if state.PermanentDelete.IsNull() {
		state.PermanentDelete = types.BoolValue(false)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, contentFromAPI(node, ver, state))...)
}

func (r *contentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state contentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	newProps, err1 := parseObject(plan.PropertiesJSON)
	oldProps, err2 := parseObject(state.PropertiesJSON)
	if err := errors.Join(err1, err2); err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("properties_json"), "Invalid JSON", err.Error())
		return
	}
	key := state.Key.ValueString()

	// 1. Move / re-own the node when requested.
	nodePatch := map[string]any{}
	if !plan.Container.IsUnknown() && plan.Container.ValueString() != state.Container.ValueString() {
		nodePatch["container"] = patchStr(plan.Container)
	}
	if !plan.Owner.IsUnknown() && plan.Owner.ValueString() != state.Owner.ValueString() {
		nodePatch["owner"] = patchStr(plan.Owner)
	}
	if len(nodePatch) > 0 {
		if _, err := r.c.PatchContent(ctx, key, nodePatch); err != nil {
			resp.Diagnostics.AddError("Updating content failed", err.Error())
			return
		}
	}

	// 2. Update the version. A published version is immutable: create a new draft.
	routeChanged := !plan.RouteSegment.IsUnknown() && plan.RouteSegment.ValueString() != state.RouteSegment.ValueString()
	dataChanged := routeChanged ||
		plan.DisplayName.ValueString() != state.DisplayName.ValueString() ||
		plan.SimpleRoute.ValueString() != state.SimpleRoute.ValueString() ||
		len(mergePatchDiff(oldProps, newProps)) > 0

	version := state.Version.ValueString()
	status := state.Status.ValueString()
	var ver *client.ContentVersion
	var err error
	switch {
	case !dataChanged:
		ver, err = r.c.GetVersion(ctx, key, version)
	case status == statusPublished:
		in := &client.ContentVersion{
			Locale: state.Locale.ValueString(), DisplayName: plan.DisplayName.ValueString(),
			SimpleRoute: plan.SimpleRoute.ValueString(), Properties: rawProps(newProps),
		}
		if !plan.RouteSegment.IsUnknown() {
			in.RouteSegment = plan.RouteSegment.ValueString()
		}
		ver, err = r.c.CreateVersion(ctx, key, in)
	default:
		patch := map[string]any{
			"displayName": plan.DisplayName.ValueString(),
			"simpleRoute": patchStr(plan.SimpleRoute),
		}
		if !plan.RouteSegment.IsUnknown() {
			patch["routeSegment"] = patchStr(plan.RouteSegment)
		}
		if props := mergePatchDiff(oldProps, newProps); len(props) > 0 {
			patch["properties"] = props
		}
		ver, err = r.c.PatchVersion(ctx, key, version, patch)
	}
	if err != nil {
		resp.Diagnostics.AddError("Updating content version failed", err.Error())
		return
	}

	// 3. Publish if requested.
	ver, err = r.publishIfRequested(ctx, key, ver, plan.Publish.ValueBool())
	if err != nil {
		resp.Diagnostics.AddError("Publishing content failed", err.Error())
		return
	}
	node, err := r.c.GetContent(ctx, key)
	if err != nil {
		resp.Diagnostics.AddError("Reading content failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, contentFromAPI(node, ver, plan))...)
}

func (r *contentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state contentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.c.DeleteContent(ctx, state.Key.ValueString(), state.PermanentDelete.ValueBool())
	if err != nil && !errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddError("Deleting content failed", err.Error())
	}
}

// ImportState accepts "key" (primary locale) or "key/locale".
func (r *contentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	key, locale, hasLocale := strings.Cut(req.ID, "/")
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("key"), key)...)
	if hasLocale {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("locale"), locale)...)
	}
}
